training: !!bool "false"
device: "cuda"
# unprocessed_data: './TIMIT/*/*/*/*.WAV'
unprocessed_data: '/data5/xin/voxceleb/raw_data/*/*/*/*.wav'
---
data:
    train_path: './train_tisv'
    # train_path_unprocessed: './TIMIT/TRAIN/*/*/*.WAV'
    train_path_unprocessed: '/data5/xin/voxceleb/raw_data/dev/*/*/*.wav'
    test_path: './test_tisv'
    # test_path_unprocessed: './TIMIT/TEST/*/*/*.WAV'
    test_path_unprocessed: '/data5/xin/voxceleb/raw_data/test/*/*/*.wav'
    # data_preprocessed: !!bool "true" 
    data_preprocessed: !!bool "false" 
    sr: 16000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 40 #Number of mel energies
    # tisv_frame: 180 #Max number of time steps in input after preprocess
    tisv_frame: 360 #Max number of time steps in input after preprocess
---   
model:
    hidden: 768 #Number of LSTM hidden layer units
    num_layer: 3 #Number of LSTM layers
    proj: 256 #Embedding size
    # proj: 1792 #Embedding size
    # model_path: './model.model' #Model path for testing, inference, or resuming training
    model_path: './1114/ckpt_epoch_130_batch_id_1498.pth'
---
train:
    N : 4 #Number of speakers in batch
    # M : 5 #Number of utterances per speaker
    M : 20 #Number of utterances per speaker
    # num_workers: 8 #number of workers for data laoder
    num_workers: 1 #number of workers for data laoder
    lr: 0.01 
    epochs: 950 #Max training speaker epoch 
    # log_interval: 30 #Epochs before printing progress
    log_interval: 1 #Epochs before printing progress
    # log_file: './speech_id_checkpoint/Stats'
    log_file: './1116_embed1792/Stats'
    # checkpoint_interval: 120 #Save model after x speaker epochs
    checkpoint_interval: 10 #Save model after x speaker epochs
    # checkpoint_dir: './speech_id_checkpoint'
    checkpoint_dir: './1116_embed1792'
    restore: !!bool "false" #Resume training from previous model path
---
test:
    N : 4 #Number of speakers in batch
    # M : 6 #Number of utterances per speaker
    M : 20 #Number of utterances per speaker
    # num_workers: 8 #number of workers for data laoder
    num_workers: 1 #number of workers for data laoder
    epochs: 1 #testing speaker epochs